#file created by script
module.exports =
  ApplicationController: require './controllers/application_controller'
  CollectionEditController: require './controllers/collection_edit_controller'
  CollectionIndexController: require './controllers/collection_index_controller'
  CustomTagComponent: require './components/custom_tag_component'
  LeftMenuComponent: require './components/left_menu_component'
  ObjectValueComponent: require './components/object_value_component'
  PaginationLinksComponent: require './components/pagination_links_component'
  SelectDropDownComponent: require './components/select_drop_down_component'
  ApplicationRoute: require './routes/application_route'
  CollectionEditRoute: require './routes/collection_edit_route'
  CollectionIndexRoute: require './routes/collection_index_route'
  CollectionRoute: require './routes/collection_route'
  Collection: require './classes/collection'
  CollectionItemClass: require './classes/collection_item_class'
